<?php /*created by language editor*/

define('T_ABOUT_US','AVIS des CLIENTS');
define('T_NEWS_EVENTS','Nouvelles');
define('T_HOME','Page d\'accueil');
define('T_TERM_CONDITION','Conditions de r&#233;servation');
define('T_CONTACT','Contactez- Nous');
define('T_LINK_EXCHANGE','Liens');
define('T_FAQ','Questionnaire');
define('T_HOT_NEWS','Unique chez nous');
define('T_BOX_TESTIMONIAL','T&#233;moignages');
define('T_VIEW_MORE','Lire la suite');
define('T_GROUP_TOUR_HOME','Circuit combin&#233; ');
define('T_TOUR_PREFERER','Circuits pr&#233;f&#233;r&#233;s');
define('T_MORE_TOUR','Lire la suite');
define('T_HOTEL_PREFERER','H&#244;tels pr&#233;f&#233;r&#233;s');
define('T_USEFUL_INFO_HOT','Guide de voyage (Montrez tous)');
define('T_TOUR','Circuits');
define('T_POLICY','Politique');
define('T_HOTEL','H&#244;tel');
define('T_SERVICE','Service');
define('T_USEFUL_INFO','Informations utiles');
define('T_ATTRACTION','Attractions');
define('T_BOX_ABOUT_US','Pourquoi Nous ?');
define('T_BOX_GALLERY','Galerie d\'entre nous');
define('T_TOP','Haut');
define('T_TOUR_IN','TOURS');
define('T_HOTEL_IN','H&#233;bergements');
define('T_TOP_GROUP_HOTEL','H&#233;bergements au');
define('T_STAR','&#233;toiles');
define('T_PRICE_FROM','Prix
&#224; partir de');
define('T_NIGHTS','nuits');
define('T_DAYS','jours');
define('T_DESTINATION','Destination');
define('T_NIGHT','nuits');
define('T_SELECT_PAGE','Page de s&#233;lection');
define('T_USEFUL_INFO_IN','Information sur');
define('T_TOUR_BOOK','Demande devis d&#233;taill&#233;');
define('T_FROM_PRICE','Prix estim&#233;');
define('T_TOUR_FROM','D&#233;but &#224;');
define('T_TOUR_STOP','Fin &#224;');
define('T_SEND_FRIEND','Envoyer &#224; vos amis');
define('T_PRIN','Imprimer');
define('T_TOUR_INCLUDE','Le prix comprend');
define('T_TOUR_EXCLUDE','Le prix ne comprend pas');
define('T_GROUP_TOUR','Voyages - Circuits');
define('T_TOUR_SIMILAR','Autres tours');
define('T_ADDRESS','Adresse');
define('T_HOTEL_BOOK','Demande devis d&#233;taill&#233;');
define('T_COUNTRY','Pays');
define('T_HOTEL_DETAIL','Informations');
define('T_HOTEL_SIMILAR','Autres h&#244;tels');
define('T_CITY','Ville');
define('T_GROUP_HOTEL','H&#244;tel');
define('T_LEFT_ARROW_KEY','Pr&#233;c&#233;dent');
define('T_MOVE','D&#233;placer');
define('T_CLOSE','Fermer');
define('T_NEXT','Suivant');
define('T_RIGHT_ARROW_KEY',' ');
define('T_RESET','Refaire');
define('T_SUBMIT','Envoyer');
define('T_GALLERY_PRODUCT','Galerie');
define('T_GROUP_SERVICE','Service');
define('T_EMAIL_TOUR_BOOK_SUBJECT_ADMIN','Demande devis du voyage');
define('T_SENDNAME','Galatourist Vietnam');
define('T_EMAIL_TOUR_BOOK_SUBJECT','Demande devis du voyage');
define('TEXT_DESCRIPTION','Circuit Vietnam Cambodge avec Galatourist- une agence locale tr&#232;s s&#233;rieuse, sp&#233;cialiste des circuits combin&#233;s &#224; vos souhaits, meilleurs services et tarifs');
define('TEXT_SITE_TITLE','Circuit Vietnam Cambodge, Voyage Vietnam Cambodge');
define('TEXT_KEYWORD','circuit vietnam cambodge, circuits vietnam cambodge, voyage vietnam cambodge, voyage vietnam cambodge pas cher');
define('T_EMAIL_TOUR_CUSTOMIZE_SUBJECT_ADMIN','Demande devis personnalise');
define('T_EMAIL_TOUR_CUSTOMIZE_SUBJECT','Demande devis personnalise');
define('T_EMAIL_HOTEL_BOOK_SUBJECT','Demande devis de l\'hotel');
define('T_EMAIL_HOTEL_BOOK_SUBJECT_ADMIN','Demande devis de l\'hotel');
define('T_TIME_CREATED','Mettre &#224; jour');
define('T_SOURCE','Source');
define('T_NEWS_EVENTS_SIMILAR','Les autres');
define('T_GROUP_USEFUL_INFO','Informations utiles');
define('T_EMAIL_CONTACT_SUBJECT_ADMIN','Contact du client');
define('T_EMAIL_CONTACT_SUBJECT','Reponse de Galatourist Vietnam');
define('T_SERVICE_BOOK','Demande de services');
define('T_SERVICE_SIMILAR','Autres Services');
define('T_GROUP_ATTRACTION','Attraction');
define('T_GROUP_LINK_EX','Lien direct');
define('T_EMAIL','Email');
define('T_NATIONAL','Nationalit&#233;');
define('T_POST','Posted');
define('T_EMAIL_TESTIMONIAL_SUBJECT','Reponse de Galatourist Vietnam');
define('T_EMAIL_TESTIMONIAL_SUBJECT_ADMIN','Avis des clients');
define('T_SEARCH','Validez');
define('T_SELECT_TOUR','Tous les circuits');
define('T_SELECT_HOTEL','Tous les h&#244;tels');
define('T_SEARCH_RESULT_TOUR','R&#233;sultat de la recherche');
define('T_KEYWORD','Mot-cl&#233;');
define('T_TYPE_TOUR','Type de voyage');
define('T_ALL','Tous');
define('T_HAVE_RESULT','R&#233;sultat');
define('T_SEARCH_RESULT_HOTEL','R&#233;sultat de la recherche');
define('T_TYPE_HOTEL','Endroit');
define('T_PREVIOUS','PREVIOUS');
define('T_BOX_SUPPORT','Aide en ligne');
define('T_MAIL_SEND_LINK_FROM','Lien envoye a votre ami(e)');
define('T_MAIL_SEND_LINK_TO','Lien envoye par votre ami(e)');
define('T_EMAIL_SERVICE_BOOK_SUBJECT','Demande de services');
define('T_TRAVEL_CONFERENCE','Voyages-Conf&#233;rences');
define('T_USEFUL_LIST','Informations utiles list');
define('T_ATTRACTION_HOT','Attraction ');
define('T_ATTRACTION_LIST','Attraction list');
define('T_TRAVEL_CONFERENCE_SIMILAR','Autres');
define('T_TOUR_CODE','Tour code');
define('T_TOUR_DETAIL',' ');
define('T_EMAIL_SERVICE_BOOK_SUBJECT_ADMIN','Demande de services');
define('T_INFO_SIMILAR','En savoir plus :');
define('T_COPYRIGHT','Galatourist.Co.,Ltd * 01-524/TCDL-GP LHQT');
define('T_REFRESH_IMAGE','Renouveler');
define('T_VIETNAM_TOUR','Tours');
define('T_TOUR_FEEDBACK','Commentaire sur circuits');
define('T_SEND_FEEDBACK','Envoyez-vos commentaires');
define('T_SEND_REVIEW_SUCESS','Votre commentaire a ete bien envoye');
define('T_EMAIL_FEEDBACK_TOUR','Commentaire sur propramme de clients');
define('T_DETAIL_TOUR','Propramme d&#233;taill&#233;');
define('T_EMAIL_CALLBACK_SUBJECT','Demande RDV t&#233;l&#233;phonique');
define('T_HOTEL_TOUR','H&#233;bergements');
define('T_TOUR_PRICE','Inclus et Exclus');
define('T_OVERVIEW_TOUR','Points forts & Bref');
define('T_SELECT_HOUR','Temps');
define('T_EMAIL_CALLBACK_SUBJECT_ADMIN','Demande RDV t&#233;l&#233;phonique');
define('T_TOUR_NEW','Nouveaux circuits');
define('T_H1_TITLE_SITE','Vietnam - Cambodge - Laos - Tha&#239;lande - Birmanie');
define('T_MENU','Menu');
define('T_VIDEO','Vid&#233;o des appr&#233;ciations');
define('ABOUT_US','montrez tous');?>