<?php //generated by esnc.net setup wizard
/**** MULTI WEBSITE SUPPORT. DISCOVER CONFIG ON DOMAIN NAME. MUST REMOVED ON DEPLOYMENT ****/
    error_reporting(0);
	return include '/home/circuitvncambod/public_html/config.php';

?>